from app.assistant import answer_user
def main():
    current_mode = None
    print("\nHey hello, I'm your Japanese-English learning assistant!")
    print("\nI can help with:")
    print("1. Translation")
    print("2. Grammar explanation")
    print("3. Vocabulary explanation")
    print("4. Mistake correction")
    print("5. Example sentences")
    print()
    print("Type 'exit' to quit.")

    while True:
        user_input = input("\nYou: ")
        user_input_lower = user_input.lower().strip()

        if user_input_lower in ["exit", "quit"]:
            print("Assistant: Bye!")
            break

        if user_input_lower in ["translate", "translation", "1"]:
            current_mode = "translate"
            print("\nAssistant:")
            print(answer_user("translate"))
            continue

        if user_input_lower in ["grammar", "2"]:
            current_mode = "grammar"
            print("\nAssistant:")
            print(answer_user("grammar"))
            continue

        if user_input_lower in ["vocabulary", "word", "explain", "3"]:
            current_mode = "vocabulary"
            print("\nAssistant:")
            print(answer_user("vocabulary"))
            continue

        if user_input_lower in ["correct", "mistake", "correction", "4"]:
            current_mode = "correction"
            print("\nAssistant:")
            print(answer_user("correct"))
            continue

        if user_input_lower in ["examples", "example", "sentences", "5"]:
            current_mode = "examples"
            print("\nAssistant:")
            print("Example sentences mode selected.")
            print("Send me a Japanese or English word, and I will generate simple example sentences.")
            continue

        if current_mode == "translate":
            print("\nAssistant:")
            print("Translation mode is active.")
            print("This sentence will be translated by the LLM in the next project step.")
            print(f"Input sentence: {user_input}")
            continue

        if current_mode == "grammar":
            print("\nAssistant:")
            print("Grammar mode is active.")
            print("This grammar question will be explained by the LLM in the next project step.")
            print(f"Input question: {user_input}")
            continue

        if current_mode == "vocabulary":
            print("\nAssistant:")
            print("Vocabulary mode is active.")
            print("This word will be explained using vocabulary data or the LLM in the next project step.")
            print(f"Input word: {user_input}")
            continue

        if current_mode == "correction":
            print("\nAssistant:")
            print("Correction mode is active.")
            print("This sentence will be corrected by the LLM in the next project step.")
            print(f"Input sentence: {user_input}")
            continue

        if current_mode == "examples":
            print("\nAssistant:")
            print("Example sentences mode is active.")
            print("Example sentences will be generated by the LLM in the next project step.")
            print(f"Input word or topic: {user_input}")
            continue

        response = answer_user(user_input)
        print("\nAssistant:")
        print(response)
if __name__ == "__main__":
    main()